-- Désactive temporairement les contraintes de clé étrangère
ALTER TABLE detailsdevis DISABLE TRIGGER ALL;
ALTER TABLE devis DISABLE TRIGGER ALL;
ALTER TABLE demande DISABLE TRIGGER ALL;
ALTER TABLE historique_status DISABLE TRIGGER ALL;

-- Truncate des tables dans l'ordre correct
TRUNCATE TABLE detailsdevis RESTART IDENTITY CASCADE;
TRUNCATE TABLE devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE demande RESTART IDENTITY CASCADE;
TRUNCATE TABLE historique_status RESTART IDENTITY CASCADE;
TRUNCATE TABLE client RESTART IDENTITY CASCADE;
TRUNCATE TABLE status RESTART IDENTITY CASCADE;
TRUNCATE TABLE typedevis RESTART IDENTITY CASCADE;

-- Réactive les triggers
ALTER TABLE detailsdevis ENABLE TRIGGER ALL;
ALTER TABLE devis ENABLE TRIGGER ALL;
ALTER TABLE demande ENABLE TRIGGER ALL;
ALTER TABLE historique_status ENABLE TRIGGER ALL;